M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu24.04.1} date 2025-01-07T12:13:39-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-07T12:13:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X151.11Y-72.225
X156.89Y-72.225
M30
